### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by AndrewJWin** [Jjeuweiii/REmibot#1]
I'm a contributor/developer for Misaki. Which is the Intellectual property of York#0001. Yet, I see no mention of any of his work in your licence. This needs to be rectified else we request this to be closed. 

All we ask is that you add York's name to your licence, as this is simply contains simple edits to remove Misaki and York from the code.

**Comment by jwchen1259** [comment]
My bad and thanks for reminding me! It must have been my Github generated file overwrote the one in his source when I init a repo from my clone but I fixed it now. I wanted to do a fork but his repo keeps giving the "You can't fork this repository at this time" error. Sorry for any misunderstanding :)
